import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const pad = (d) => {
  return (d < 10) ? '0' + d.toString() : d.toString();
}

const questionBtn = (props) => {
  return (
    <Link href={ `/answer/number-${props.key < 5 ? props.key : props.key == 9 ? 9 : 5}` } passHref key={props.key}>
      <a className='inline-flex'><code className={`${styles.code} hover:shadow-lg`}>Soal {pad(props.key)}.</code></a>
    </Link>
  )
}

export default function Home() {
  let questions = []
  for (let i = 1; i <= 10; i++) {
    questions.push(questionBtn({ key: i }));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Azlogistic Trial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          FRONT-END ASSIGNMENT
        </h1>

        <p className={`${styles.description} grid grid-cols-5 gap-2`}>
          { questions }
        </p>
      </main>

      <footer className={styles.footer}>
          Powered by Muhammad Arijuddin
      </footer>
    </div>
  )
}
